export const cardArray = [
  {
    id: 0,
    title: "Товар первый",
    price: "170 ₽",
    address: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    imgSrc: "/image/card_img.png",
    imgAlt: "Card",
  },
  {
    id: 1,
    title: "Товар второй",
    price: "171 ₽",
    address: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    imgSrc: "/image/card_img.png",
    imgAlt: "Card",
  },
  {
    id: 2,
    title: "Товар третий",
    price: "172 ₽",
    address: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    imgSrc: "/image/card_img.png",
    imgAlt: "Card",
  },
  {
    id: 3,
    title: "Товар четвёртый",
    price: "173 ₽",
    address: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    imgSrc: "/image/card_img.png",
    imgAlt: "Card",
  },
  {
    id: 4,
    title: "Товар пятый",
    price: "174 ₽",
    address: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    imgSrc: "/image/card_img.png",
    imgAlt: "Card",
  },
  {
    id: 5,
    title: "Товар шестой",
    price: "175 ₽",
    address: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    imgSrc: "/image/card_img.png",
    imgAlt: "Card",
  },
];

export const serviceArray = [
  {
    id: 0,
    imgSrc: "/image/side_info_1.svg",
    imgAlt: "Side Info 1",
    title: "Доставка",
    text: "Проверка при получении и возможность бесплатно вернуть товар",
  },
  {
    id: 1,
    imgSrc: "/image/side_info_2.svg",
    imgAlt: "Side Info 2",
    title: "Автотека",
    text: "Отчёт с историей авто: пробег, владельцы, сведения о залоге, ДТП и ремонтах",
  },
  {
    id: 2,
    imgSrc: "/image/side_info_3.svg",
    imgAlt: "Side Info 3",
    title: "Онлайн-бронирование жилья",
    text: "Посуточная аренда квартир и домов: большой выбор вариантов для поездок по России",
  },
];
